<a href="https://colab.research.google.com/github/geetakotur/hey/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arrayvalue = np.empty([3,2],dtype=int)
print(arrayvalue)

[[94842274652080              0]
 [             0              0]
 [             0              0]]


In [5]:
import numpy as np
samplearray=np.array([[1,2,3],[4,5,6]])
samplearray.shape=(3,2)
print(samplearray)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
import numpy as np
samplearray=np.array([[1,2,3],[4,5,6]])
samplearray.shape=(2,3)
print(samplearray)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
samplearray=np.array([[1,2,3],[4,5,6]])
samplearray.shape=(1,6)
print(samplearray)

[[1 2 3 4 5 6]]


In [10]:
import numpy as np
samplearray=np.array([[8,10.2,-3.5],[-4,5.125,-6.258]])
samplearray.shape=(3,2)
print(samplearray)
samplearray.shape=(2,3)
print(samplearray)
samplearray.shape=(1,6)
print(samplearray)
samplearray.shape=(6,1)
print(samplearray)

[[ 8.    10.2  ]
 [-3.5   -4.   ]
 [ 5.125 -6.258]]
[[ 8.    10.2   -3.5  ]
 [-4.     5.125 -6.258]]
[[ 8.    10.2   -3.5   -4.     5.125 -6.258]]
[[ 8.   ]
 [10.2  ]
 [-3.5  ]
 [-4.   ]
 [ 5.125]
 [-6.258]]


In [13]:
import numpy as np
samplearray=np.array([2,3,4,4,4,4,5,5,6,7,7,8,9,9,9,9,10,11,12,12])
print(samplearray)
print(np.min(samplearray))
print(np.max(samplearray))
print(np.mean(samplearray))
print(np.median(samplearray))
print(np.std(samplearray))


[ 2  3  4  4  4  4  5  5  6  7  7  8  9  9  9  9 10 11 12 12]
2
12
7.0
7.0
2.9832867780352594
